main:
  - name: Home
    url: '/#'
    weight: 10
  - name: Students
    url: '#students'
    weight: 30
  - name: Employers
    url: '#employers'
    weight: 40
  - name: Seminar
    url: '#seminar'
    weight: 45
  - name: Stories
    url: '#posts'
    weight: 50
  - name: People
    url: '#people'
    weight: 60
  - name: Editions
    url: '#editions'
    weight: 70
  - name: Contact
    url: '/#contact'
    weight: 80

